name: Docs

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v1
        id: cache-node-modules
        with:
          path: node_modules
          key: node-12.x-${{ hashFiles('**/package.json') }}
          restore-keys: |
            node-${{ matrix.node-version }}-
      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
      - run: npm run build:docs
      - run: echo "::set-env name=PACKAGE_VERSION::${{ cat package.json | jq '.version' }}"
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: "docs-api-v"
          path: api
